backend:
  name: git-gateway
  branch: main # Replace with your Git branch name

media_folder: "public/images/uploads"  # Where uploaded images will go
public_folder: "/images/uploads"       # Public path for images

collections:
  - name: "movies"
    label: "Movies"
    folder: "content/movies"  # Folder to save movie posts
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Movie Link", name: "link", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }