backend:
  name: git-gateway
  branch: main # Replace with your Git branch name

media_folder: "public/images/uploads"  # Where uploaded images will go
public_folder: "/images/uploads"       # Public path for images

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
